### ISSUE TITLE
Extra Readme?

### ISSUE THREAD

**Issue by KrazyKirby99999** [IanTerzo/Neutron#13]
There is both a readme and a pypi readme. This is unnecessary and it is possible to use a single readme for both purposes.

**Comment by KrazyKirby99999** [comment]
You can add `readme = "README.md"` to the pyproject.toml under the `[tool.poetry]` section on the `poetry-package` branch.

**Comment by IanTerzo** [comment]
✔️ Deleted unnecessary pypi readme
