### ISSUE TITLE
How to include local images in my application 

### ISSUE THREAD

**Issue by jfgauron** [IanTerzo/Neutron#14]
Hello, I'm unclear how I can add images to my application. Let's say my `render.html` looks like this:

```
<!DOCTYPE html>
<html>
   <body>
      <img src="PATH/TO/IMG" />
   </body>
</html>
```

What would `PATH/TO/IMG` be? Giving it an absolute path to an online image would of course work but what if I want to have my image included in the executable? Thanks.

**Comment by IanTerzo** [comment]
You can now include local images in Neutron's new version. `pip install Neutron-Web --upgrade`
Example:
`<img src="yourfile.png" />`

Note that it doesn't work with absolute paths

**Comment by jfgauron** [comment]
That was quick, thank you!

**Comment by manatlan** [comment]
@jfgauron ... seems to be broken now, in 0.1.6 .. no ?!
