### ISSUE TITLE
Single quote in rendered HTML results in SyntaxError: unterminated string literal

### ISSUE THREAD

**Issue by RalfG** [IanTerzo/Neutron#16]
HTML rendered with `Window.display(file="<html file>")` can currently not contain single quotes, as single quotes are used to construct the f-string:

https://github.com/IanTerzo/Neutron/blob/425d4edfe39271a95cf94b8f442fc7a496f185d4/Neutron/__init__.py#L118

The following HTML file results in an error:

```html
<!DOCTYPE html>
<html>
   <head>
   </head>
   <body>
      <p>Single quote: '</p>
   </body>
</html>
```

```
SyntaxError: unterminated string literal (detected at line 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ralf\Desktop\neutron_test\neu.py", line 7, in <module>
    win.display(file="index.html")
  File "C:\Users\ralf\Miniconda3\envs\neutron\lib\site-packages\Neutron\__init__.py", line 108, in display
    raise WindowException("Error while parsing python code inside -> { }. Error: " + str(e))
Neutron.WindowException: Error while parsing python code inside -> { }. Error: unterminated string literal (detected at line 1) (<string>, line 1)
```

**Comment by IanTerzo** [comment]
This is resolved in Neutrons latest version: `pip install Neutron-Web==0.1.5`

**Comment by RalfG** [comment]
Thanks for taking a look at this! Single quotes now indeed work. However, now a succession of three single quotes `'''` results in the same problem. I'm not sure if this would be an issue in practice, but it's good to know.
