### ISSUE TITLE
What is the purpose/goal of neutron ?

### ISSUE THREAD

**Issue by manatlan** [IanTerzo/Neutron#17]
Hi @IanTerzo  ...

Perhaps, i'm completly dumb ... But I was really enthusiast when reading a reddit post about neutron.
But now, than I'm testing the lib ; I can't see the benefits over pywebview ?!
On the contrary, it seems it just gives a limited scope of pywebview ?!?
It just implement a httpserver, and some good(/limited) practice ...
Or perhaps it's just the beginning, and your plan to add a lot of things ?

I'm trying to mix pywebview+brython ... and have some good result yet !
(first try with neutron+brython, but no ways)

BTW, thanks for redirecting me to the marvelous pywebview (which is, clearly an underated module) !

**Comment by IanTerzo** [comment]
Hey, 
Neutron is meant to be an easy way to create GUI's using web technologies. In pywebview you need to use JavaScript in many situations, while Neutron is trying to remove the necessity for that, this is achieved by making the syntax as close as it would be when creating a vanilla website, by bringing the DOM to Python. For example, in pywebview, to run python code on a button click you need to set up and communicate with an API, than probably communicate back the result to JavaScript, where you can use it again. By implementing the DOM in Python Neutron removes the need for an intermediary JavaScript file. Neutron also allows to create an entire project in a single python file, this is good if you are planning to make a small and portable project. 

New features are also being planned, for example a build tool, a system for creating custom web components and also brython integration, thanks for asking.
