### ISSUE TITLE
Some setup issues I had

### ISSUE THREAD

**Issue by eharshman** [IanTerzo/Neutron#19]
Hello,

While trying to run your example scripts, I ran into some problems but was able to fix most of them, so I thought I'd share.

In Readme.md, the second and third example scripts contain `{Neutron.Button` but this proved to be invalid. I changed it to `{Neutron.elements.Button` to resolve the issue.

I got an error indicating that I had to install a parser for lxml in order for the BeautifulSoup functionality to work. I installed the python package called 'lxml' to resolve that one.

I got a pywebview error stating that the edgehtml renderer was deprecated, and that I needed to get edge_chromium. I downloaded the [Evergreen WebView2](https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section) installer and ran that to resolve the issue.

I still have not managed to get pyinstaller to work using the command provided in the documentation. I get the following traceback info:

```
pyinstaller /NEUTRON_DEMO/neutrondemo.py --noconsole --onefile --add-data="/NEUTRON_DEMO/render.html;." --add-data="/NEUTRON_DEMO/def.css;."
Traceback (most recent call last):
  File "C:\Python\Python38\lib\code.py", line 63, in runsource
    code = self.compile(source, filename, symbol)
  File "C:\Python\Python38\lib\codeop.py", line 178, in __call__
    return _maybe_compile(self.compiler, source, filename, symbol)
  File "C:\Python\Python38\lib\codeop.py", line 106, in _maybe_compile
    raise err1
  File "C:\Python\Python38\lib\codeop.py", line 93, in _maybe_compile
    code1 = compiler(source + "\n", filename, symbol)
  File "C:\Python\Python38\lib\codeop.py", line 143, in __call__
    codeob = compile(source, filename, symbol, self.flags, 1)
  File "<input>", line 1
SyntaxError: cannot assign to operator
```

**Comment by IanTerzo** [comment]
Is this the full error message? Also what version of pyinstaller are you using?

**Comment by eharshman** [comment]
I believe that was the full message. I am using pyinstaller 5.0

**Comment by GeorgeDavila** [comment]
pyinstaller is often a pain, try installing it directly from source 

pip install https://github.com/pyinstaller/pyinstaller/tarball/develop

**Comment by simonepuglisi** [comment]
Thank you man, do you know how use proxy? I need that but I cannot insert into this project, if you can add me on ***@***.*** from Yandex Mail for mobile20.04.2022, 10:29 PM, "eharshman" ***@***.***>:
Hello,
While trying to run your example scripts, I ran into some problems but was able to fix most of them, so I thought I'd share.
In Readme.md, the second and third example scripts contain {Neutron.Button but this proved to be invalid. I changed it to {Neutron.elements.Button to resolve the issue.
I got an error indicating that I had to install a parser for lxml in order for the BeautifulSoup functionality to work. I installed the python package called 'lxml' to resolve that one.
I got a pywebview error stating that the edgehtml renderer was deprecated, and that I needed to get edge_chromium. I downloaded the Evergreen WebView2 installer and ran that to resolve the issue.
I still have not managed to get pyinstaller to work using the command provided in the documentation. I get the following traceback info:
pyinstaller /NEUTRON_DEMO/neutrondemo.py --noconsole --onefile --add-data="/NEUTRON_DEMO/render.html;." --add-data="/NEUTRON_DEMO/def.css;."
Traceback (most recent call last):
  File "C:\Python\Python38\lib\code.py", line 63, in runsource
    code = self.compile(source, filename, symbol)
  File "C:\Python\Python38\lib\codeop.py", line 178, in __call__
    return _maybe_compile(self.compiler, source, filename, symbol)
  File "C:\Python\Python38\lib\codeop.py", line 106, in _maybe_compile
    raise err1
  File "C:\Python\Python38\lib\codeop.py", line 93, in _maybe_compile
    code1 = compiler(source + "\n", filename, symbol)
  File "C:\Python\Python38\lib\codeop.py", line 143, in __call__
    codeob = compile(source, filename, symbol, self.flags, 1)
  File "<input>", line 1
SyntaxError: cannot assign to operator
