### ISSUE TITLE
html <input> properties

### ISSUE THREAD

**Issue by eharshman** [IanTerzo/Neutron#20]
Hello,

I am trying to use an html file picker button <input type="file"> to choose a file and use the resulting file path within python code.

However, it does not appear that the required attributes of the input element are being carried over through neutron from the html. There should be a 'Files' attribute which is a container for the path or paths of the files chosen using the input element.

There are several other 'additional' attributes of the input element which appear to be missing, as well. From the HTML documentation: [<input type="file"> Additional Attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#additional_attributes)

If I knew how to fix it, I would take a swing at it myself. If someone corrects the input element I could use that as an example and correct any others I find.

Side note, in HTML the input element is actually of the type HTMLInputElement, not HTMLElement. I'm not sure if that distinction is necessary within Neutron.

From the HTML documentation:
The selected files are returned by the element's HTMLInputElement.files property, which is a [FileList](https://developer.mozilla.org/en-US/docs/Web/API/FileList) object containing a list of File objects. The FileList behaves like an array, so you can check its length property to get the number of selected files.

**Comment by IanTerzo** [comment]
This should be solved by adding "Files" and the other additional attributes to the `HTMLelementAttributes` list in the [elements](https://github.com/IanTerzo/Neutron/blob/main/Neutron/elements.py) file. If possible could you clone this repo and try that? (Just make sure to rename the Neutron folder to something different to avoid errors when importing it.)

If not could you share your code so i can reproduce your error and make sure the solution above works?

**Comment by eharshman** [comment]
Sorry for the delay - I was on vacation last week.

I have never installed a package without using pip, so I am not sure how to use a cloned repo the way you described.

I did try to add the 'files' attribute to the `HTMLelementAttributes` list in my local Neutron installation, which does add a files attribute to the file picker button, however it's of the 'str' type and has no file path objects beneath it after picking a file.

I am wondering if we also need to define the 'File' object(s) within the 'Files' property (as described at the bottom of my initial post), or possibly change the data type from 'str' to something else, but I'm not sure how we would do that.

I'm attaching my demo code, in which I am supplying a file and once 'Open' is clicked, the below text should be changed programmatically to show the path to the chosen file.

[file picker test.zip](https://github.com/IanTerzo/Neutron/files/8605042/file.picker.test.zip)

**Comment by IanTerzo** [comment]
Hello,
Sorry for not responding sooner i had a busy week and did not check my Github.

I looked into the problem and realized that the only way to solve it is to add a new function to the `HTMLelement` class that gets all the files of the input using JavaScript and then returns them to Python as a list. I can then work the function into an attribute using the built-in function `property()`.

If you want you could try implementing this yourself (take a look at how the `innerHTML_get` function works), otherwise i will add it myself probably during this week.

**Comment by DiegoAscanio** [comment]
Well, i made an workaround through arbitrary javascript execution by window.webview.evaluate_js and a hidden input tag to store b64 encoding from a file. Please take a look at my base template and my carregar_cartoes function, they might offer some help:

`def carregar_cartoes():
    # ler cartoes do arquivo atraves de javascript

    # 1. definir funcao javascript que converte o arquivo em b64 e atribui este valor para o input hidden
    b64_js = '''
        function b64(file) {
            reader = new FileReader();
            reader.readAsDataURL(file); 
            reader.onload = function(event) {
                document.getElementById('cartoes_b64').value = event.target.result.split(',')[1];
            }
        }
    '''
    __eval_js_statement(b64_js)

    # 2. ler planilha do input file em javascript, atribuindo o input hidden
    __eval_js_statement('b64(document.getElementById(\'carregar_cartoes\').files[0]);')

    # 3. carregar dataframe de cartoes a partir do input hidden da pagina
    planilha_b64 = config.window.getElementById('cartoes_b64').value
    config.cartoes = pd.read_excel(base64.b64decode(planilha_b64))

    # 4. desabilita input da planilha e habilita input para iniciar procedimento
    input_planilha = config.window.getElementById('carregar_cartoes')
    input_planilha.disabled = True
    btn_iniciar = config.window.getElementById('iniciar')
    pdb.set_trace()
    btn_iniciar.disabled = False`

`<html>
	<head>
		<title>Associar Cartões TAGs</title>
	</head>
	<body>
		<input type='hidden' id='cartoes_b64' />
		<center>
			<table>
				<tr>
					<td colspan = 2 style='text-align: center'><h3>Pessoa</h3></td>
				</tr>
				<tr>
					<td colspan = 2 style='text-align: center' id='pessoa'></td>
				</tr>
				<tr>
					<td colspan = 2 style='text-align: center'><h3>TAG</h3></td>
				</tr>
				<tr>
					<td colspan = 2 style='text-align: center'><input type='text' id='tag' disabled /></td>
				</tr>
				<tr>
					<td style='text-align: center'><input type='button' id='retroceder' value='Retroceder' disabled /></td>
					<td style='text-align: center'><input type='button' id='avancar' value='Avançar' disabled /></td>
				</tr>
				<tr>
					<td style='text-align: center' colspan=2><input type='file' accept='.xls' id='carregar_cartoes' value='Upload Planilha' /></td>
				</tr>
				<tr>
					<td style='text-align: center' colspan=2><input type='button' id='iniciar' value='Iniciar' disabled/></td>
				</tr>
				<tr>
					<td style='text-align: center' colspan=2><input type='button' id='salvar_alteracoes' value='Salvar Alteracoes' disabled /></td>
				</tr>
			</table>
		</center>
	</body>
</html>`

**Comment by DiegoAscanio** [comment]
Here it is the more elegant solution, using pywebview openfile dialog:

<script src="https://gist.github.com/DiegoAscanio/6502ec8c9794653068ea4a11f2f71a12.js"></script>

**Comment by DiegoAscanio** [comment]
[Neutron openfiledialog with pywebview's file dialog](https://gist.github.com/DiegoAscanio/6502ec8c9794653068ea4a11f2f71a12)
