### ISSUE TITLE
Can't install 

### ISSUE THREAD

**Issue by phamorim182** [IanTerzo/Neutron#27]
I tried using pip install neutorn-web and then pyinstaller YOUR_PYTHON_FILE.py --noconsole --onefile --add-data="YOUR_HTML_FILE.html;." --add-data="YOUR_CSS_FILE.css;.", but the latter gives me some errors.
First it said "YOUR_PYTHON_FILE.py" not found, so, to avoid this type of error, i created the files YOUR_PYTHON_FILE.py, YOUR_PYTHON_FILE.html, YOUR_PYTHON_FILE.css on the directory. Then, the pyinstaller line runs normally on cmd, but when i try to use the import Neutron, it still wont work ( No module named 'Neutron').
I don't know what i am doing wrong, and coudn't solve this.

**Comment by IanTerzo** [comment]
Pyinstaller is used to convert a python file or project into an executable, aka **building** it. So the second command you entered is useless unless you have a python file named YOUR_PYTHON_FILE.py that you want to turn into an executable.

The "No module named" error means that python doesn't find a certain module. Try to instead install the module using `python -m pip install neutron-web`, and then try running your python file using `python THENAMEOFTHEFILE.py` in cmd.

Let me know if it works.

**Comment by phamorim182** [comment]
Thanks for the help, and sorry for the beginner question.
It now works fine when i run it on CMD. I can also build the exe file using pyinstaller (using the template project) , but when i open the file it returns the following error:
Failed to execute script 'main' due to unhandled exception
Traceback (most recent call last):
  File "main.py", line 4, in <module>
  File "Neutron\__init__.py", line 128, in display
UnboundLocalError: local variable 'soup_src' referenced before assignment

**Comment by Jkkarr2015** [comment]
I'm seeing the same issue after having built an executable with pyinstaller.

**Comment by IanTerzo** [comment]
> 

Update to the latest version using: `pip install neutron-web --upgrade`
