### ISSUE TITLE
UnboundLocalError: local variable 'soup_src' referenced before assignment

### ISSUE THREAD

**Issue by Jkkarr2015** [IanTerzo/Neutron#28]
Hello,

I'm making this ticket which was mentioned in issue #27, but is fundamentally a different issue entirely and should be treated as such. Both @phamorim182 and myself have experienced this issue. 

After building standalone executable files using pyinstaller and the following instruction:  `pyinstaller YOUR_PYTHON_FILE.py --noconsole --onefile --add-data="YOUR_HTML_FILE.html:." --add-data="YOUR_CSS_FILE.css:."` The resulting executable gives the following error after opening:

Failed to execute script 'main' due to unhandled exception
Traceback (most recent call last):
File "main.py", line 4, in
File "Neutron_init_.py", line 128, in display
UnboundLocalError: local variable 'soup_src' referenced before assignment

The mentioned line can be found here: https://github.com/IanTerzo/Neutron/blob/d150d9c9effa291998564d6d5f0d00e39b94b18e/Neutron/__init__.py#L128

By looking at the code it seems that for some reason the `soup_src` variable is not getting set in the above `if/elif` statement presumably the `file` parameter is not set and neither is `html` parameter. 

I have run into this issue on both a Mac and Ubuntu machine. If any more information is needed please let me know.

**Comment by IanTerzo** [comment]
Thanks for letting me know about this issue, I was not able to reproduce the error so I need to know some information:
1. Are you on the latest version (**0.2.2.1**)? `pip show neutron-web` to see what version you are using
2. What does your code look like? You don't need to show everything just the part that makes it run

**Comment by Jkkarr2015** [comment]
@IanTerzo 
 
I am running latest version 0.2.2.1.

Here is my code:

```python
import Neutron

win = Neutron.Window("App Name", css="app.css")
win.display(file="app.html")

win.show()

**Comment by IanTerzo** [comment]
This issue was actually already solved by @DiegoAscanio,
I have now uploaded the fix and you can get it by running pip install neutron-web --upgrade

**Comment by Jkkarr2015** [comment]
Cool. Thank you.
