### ISSUE TITLE
TypeError: create_window() got an unexpected keyword argument 'html'

### ISSUE THREAD

**Issue by Jkkarr2015** [IanTerzo/Neutron#29]
Hello,

I'm trying to use Neutron on Raspbian OS and I can't get the python script to run because of this error: 
`TypeError: create_window() got an unexpected keyword argument 'html'` 
and it says the issue is here https://github.com/IanTerzo/Neutron/blob/e8806003ba2598ac81def57bbe11b41b32fd4b91/Neutron/__init__.py#L79

I'm using Neutron version 0.3

My python code looks like this:
```python
import Neutron

win = Neutron.Window("App", css="welcome.css")
win.display(file="welcome_app.html")

win.show()

```

Am I doing something wrong? Does Neutron not work on Raspbian OS? I have no problem running this same code on my Macbook.

**Comment by IanTerzo** [comment]
What version of pywebview are you using? `py -m pip show pywebview`
Make sure it's the latest version `3.7.2`

**Comment by Jkkarr2015** [comment]
That seems to have been the issue. It was not the most current version. Sorry about that.
