### ISSUE TITLE
Not working properly when creating a second window

### ISSUE THREAD

**Issue by lucasadsouza** [IanTerzo/Neutron#31]
When I try create a second window, the first window works properly, but the second window when I try to open by a function it just opens completely white.

![image](https://user-images.githubusercontent.com/50783437/206798107-f36bba99-a4ed-406f-b4a2-c0b36bf1cf88.png)

```python
def testfunc():
  win2 = Neutron.Window('Test2', size=(600, 450))
  win2.display(file='screen2.html')
  win2.show()

win.display(file='index.html', pyfunctions=[testfunc])

win.show()

```

If I declare the window outside the function and just call the show method inside the function, it just opens right at the start...

**Comment by IanTerzo** [comment]
Sorry for the wait, this is fixed in the latest version 0.3.1
```py
def testfunc():
  win2 = Neutron.Window('Test2', size=(600, 450), childwindow=True)
  win2.display(file='screen2.html')
  win2.show()

win.display(file='index.html', pyfunctions=[testfunc])

win.show()
```
When you are creating a window that is not the main one you need to use the `childwindow` argument as shown above.

You can get the latest version by running `pip install neutron-web --upgrade`.
