### ISSUE TITLE
How to use in python <div> to create CSS grids? 

### ISSUE THREAD

**Issue by Zamy846692** [IanTerzo/Neutron#38]
There dosen't seem to be any documentation or examples of how to add `<div>` elements dynamically from python, I was able to add `<p>` elements dynamically form a python scrip using def P, but haven't been able to figure out how to do the same with def Div.
If the grid itself was in the `render.html` file it would look something like this:
````
<div class=table table--fit>
   <div class=box> variable </div>
   <div class=box> variable </div>
   <div class=box> variable </div>
</div>
````
I wanted to display variables my script generated in the CSS grid, so I would need add the `<div>` elements from the python file itself to the window are there any examples of this, cheers

**Comment by IanTerzo** [comment]
If I understood correctly, you want to insert a div within the table container, is that right?

Can't you just append the div to the table?
```
def add():
    getElementById("givethedivanid").append("<div class=box> variable </div>")

```
