### ISSUE TITLE
Charset UTF-8

### ISSUE THREAD

**Issue by nilsonec2015** [IanTerzo/Neutron#44]
it is not displaying special characters.
include **encoding="utf-8"** to correct in lines 120 and 122

__init__.py 

            if getattr(sys, 'frozen', False):
                content = str(open(os.path.join(sys._MEIPASS, file), "r", encoding="utf-8").read())
            else:
                content = str(open(file, "r", encoding="utf-8").read())

**Comment by IanTerzo** [comment]
Fixed in https://github.com/IanTerzo/Neutron/commit/932af20d87166005f80233049203760aac638d4e
