### ISSUE TITLE
Testing to build on Linux/MacOS

### ISSUE THREAD

**Issue by IanTerzo** [IanTerzo/Neutron#5]
https://github.com/IanTerzo/Neutron#building 
If you are a Linux/MacOS user please let us know if you can build a project or if you stumble upon any issues.

**Comment by ritznotcrackers** [comment]
# Testing to build on Linux

Hello, I'm still quite new to programming and python in general. While I was searching the internet for what games can be made and are made with pygame, I saw someone on [Reddit](https://www.reddit.com/r/Python/comments/rofw96/you_can_now_make_python_desktop_apps_with_html/?utm_source=share&utm_medium=web2x&context=3) posted a link to your project and got curious. I am running KDE Neon and tried out Neutron, below are screenshots and code to what I did. I hope this can help.

### Folder structure

I used `pipenv` to create a virtual environment and install both `Neutron-Web` and `pyinstaller`. I've separated the `main.py`, `render.html`, and `def.css` and put them into a folder called `src/`

![image](https://drive.google.com/uc?export=view&id=1gv8TvCqs8jTi6JUIiFVjztTmLxfqr5_c)

### Source code

**main.py**
```python
import Neutron

win = Neutron.Window("Neutron", size=(600, 100), css="def.css")
win.display(file="src/render.html")

# Get elements
my_message = win.getElementById("my-message")
input_name = win.getElementById("input-name")
submit_name = win.getElementById("submit-name")

def DisplayMessage():
	my_message.innerHTML = f"Hello {input_name.value}, I am testing Neutron."


submit_name.AddEventListener("click", Neutron.event(DisplayMessage))


win.show()
```

**render.html**

```html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>
<body>
	<h1 id="my-message">Hello, </h1>
	<input id="input-name">
	<button id="submit-name"></button>
</body>
</html>
```

**def.css**

```css
body {
	color: blue;
}
```

### Build output

I followed the guide on the the repo's homepage to build and below is the output. I don't know if I did something wrong.

![image](https://drive.google.com/uc?export=view&id=1t95N04-YwjYEd89lGJ7qLzvf12Bq672-)

I hope this helps.

**Comment by IanTerzo** [comment]
Looking at pyinstallers documentation ";" should be ":" in Linux, 
Try this:
`pyinstaller src/main.py --noconsole --onefile --add-data="src/render.html:." --add-data="src/def.css:." `
If that doesn't work try adding:
`--hidden-import pywebview --hidden-import beautifulsoup4 --hidden-import keyboard`

**Comment by ritznotcrackers** [comment]
It worked! Nice :+1:
