### ISSUE TITLE
Keyboard Library requires root (admin) permission to use on Linux

### ISSUE THREAD

**Issue by KrazyKirby99999** [IanTerzo/Neutron#6]
The root requirement for the keyboard library makes Neutron a less attractive option. Would it be possible to remove all usage of the keyboard library?

It is only used in one particular line, where it appears to be preventing the F5 key from being used.
https://github.com/IanTerzo/Neutron/blob/c7a4874e9dba1696526bbf68ff11d1f3e13ad6e4/Neutron/__init__.py#L123

**Comment by IanTerzo** [comment]
It is used to prevent the user from refreshing the page, not sure if that applies on Linux too. 

Maybe replacing "import keyboard" with
```
from sys import platform
if platform != "linux" or platform != "linux2": import keyboard
```
would disable keyboard from the Linux version and thus not require administrator permissions? Could you try it and send an update comment ?

**Comment by KrazyKirby99999** [comment]
#7

**Comment by KrazyKirby99999** [comment]
While this does make your library no longer require root access, it creates a problem in that it behaves slightly differently on windows and linux. You may want to consider if the following is neccesary.
```
            keyboard.block_key("f5")
```

**Comment by IanTerzo** [comment]
https://github.com/IanTerzo/Neutron/pull/7
